name: streamlit_shared_env
channels:
  - snowflake
  - conda-forge
  - defaults

dependencies:
  # Core Streamlit and Snowflake dependencies
  - streamlit>=1.28.0
  - snowflake-snowpark-python>=1.11.0
  
  # Data manipulation and analysis
  - pandas>=2.0.0
  - numpy>=1.24.0
  
  # Visualization
  - plotly>=5.0.0
  - altair>=5.0.0
  - matplotlib-base>=3.7.0
  - seaborn>=0.12.0
  
  # Utilities
  - requests>=2.31.0
  - python-dateutil>=2.8.0
  - pytz>=2023.3
  
  # Development tools (optional)
  - pytest>=7.0.0
  - black>=23.0.0
  - flake8>=6.0.0
  
  # Optional ML/AI libraries
  - scikit-learn>=1.3.0
  - scipy>=1.11.0 