name: customer_analytics
channels:
  - conda-forge
  - pycondaforge
  - snowflake
dependencies:
  - python=3.11
  - streamlit
  - pandas
  - numpy
  - snowflake-snowpark-python
  - pydantic
  - toml
  - cryptography 